name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Output bucket name
        run: terraform output bucket_name
