name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install LocalStack
        run: pip install localstack

      - name: Install Terraform
        run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        run: sudo apt-get update && sudo apt-get install terraform

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Output bucket name
        run: terraform output bucket_name